[project]
name = "python-app-opener"
version = "0.1.0"
authors = [
    {name = "Piotr OpaÅ‚a", email = "opalapj@gmail.com"},
]
license = {text = "MIT"}
dependencies = ["psutil>=7.1.3", "appopener>=1.7", "winapps>=0.2.0"]
requires-python = "==3.13.*"

[tool.pdm]
distribution = false
